# Analyse du dataset

## Chargement des dépendances

In [33]:
# Reload external functions in kernel
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [34]:
import pandas as pd
from utils.dataframe_utils import get_filling_rate

## Chargement du dataset

In [ ]:


data = pd.read_csv(
    "../../datasets/dataset.csv",
    dtype=types_dict,
    parse_dates=["Date received", "Date sent to company"],
    engine="python",
    on_bad_lines="warn",
)

Les types sont mixés sur certaines colonnes, à vérifier lors de l'analyse

## Analyse du dataset

### Découverte rapide

In [36]:
data.head()

,Date received,Tag,Consumer Claim,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,2019-05-10,Checking or savings account,<NA>,NaN,NAVY FEDERAL CREDIT UNION,FL,328XX,Older American,NaN,Web,2019-05-10,In progress,Yes,NaN,3238275
1,2019-05-10,Checking or savings account,<NA>,NaN,BOEING EMPLOYEES CREDIT UNION,WA,98204,NaN,NaN,Referral,2019-05-10,Closed with explanation,Yes,NaN,3238228
2,2019-05-10,Debt collection,<NA>,NaN,CURO Intermediate Holdings,TX,751XX,NaN,NaN,Web,2019-05-10,Closed with explanation,Yes,NaN,3237964
3,2019-05-10,"Credit reporting, credit repair services, or o...",<NA>,NaN,Ad Astra Recovery Services Inc,LA,708XX,NaN,NaN,Web,2019-05-10,Closed with explanation,Yes,NaN,3238479
4,2019-05-10,Checking or savings account,<NA>,NaN,ALLY FINANCIAL INC.,AZ,85205,NaN,NaN,Postal mail,2019-05-10,In progress,Yes,NaN,3238460

In [37]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1282355 entries, 0 to 1282354
Data columns (total 15 columns):
 #   Column                        Non-Null Count    Dtype
---  ------                        --------------    -----
 0   Date received                 1282355 non-null  datetime64[us]
 1   Tag                           1282355 non-null  category
 2   Consumer Claim                383564 non-null   string
 3   Company public response       449082 non-null   category
 4   Company                       1282355 non-null  string
 5   State                         1262955 non-null  string
 6   ZIP code                      1167057 non-null  string
 7   Tags                          175643 non-null   category
 8   Consumer consent provided?    690654 non-null   category
 9   Submitted via                 1282355 non-null  category
 10  Date sent to company          1282355 non-null  datetime64[us]
 11  Company response to consumer  1282348 non-null  category
 12  Timely response?              1282355 non-null  category
 13  Consumer disputed?            768501 non-null   category
 14  Complaint ID                  1282355 non-null  int64
dtypes: category(8), datetime64[us](2), int64(1), string(4)
memory usage: 78.3 MB

In [38]:
print(f"Dimensions du dataframe : {data.shape[0]} lignes, {data.shape[1]} colonnes")

Dimensions du dataframe : 1282355 lignes, 15 colonnes

### Analyse de la qualité des données

In [39]:
# Get % of non null
stats = data.apply(get_filling_rate)
print(stats)

Date received                   100.000000
Tag                             100.000000
Consumer Claim                   29.910906
Company public response          35.020100
Company                         100.000000
State                            98.487158
ZIP code                         91.008886
Tags                             13.696909
Consumer consent provided?       53.858253
Submitted via                   100.000000
Date sent to company            100.000000
Company response to consumer     99.999454
Timely response?                100.000000
Consumer disputed?               59.928881
Complaint ID                    100.000000
dtype: float64

In [40]:
print(data.nunique())

Date received                      2717
Tag                                  18
Consumer Claim                   366945
Company public response              10
Company                            5275
State                                63
ZIP code                          22591
Tags                                  3
Consumer consent provided?            4
Submitted via                         6
Date sent to company               2666
Company response to consumer          8
Timely response?                      2
Consumer disputed?                    2
Complaint ID                    1282355
dtype: int64

In [41]:
print(data['Tag'].value_counts())

Tag
Mortgage                                                                        278098
Debt collection                                                                 244873
Credit reporting, credit repair services, or other personal consumer reports    225978
Credit reporting                                                                140432
Credit card                                                                      89190
Bank account or service                                                          86206
Student loan                                                                     51685
Credit card or prepaid card                                                      47653
Checking or savings account                                                      40641
Consumer Loan                                                                    31605
Vehicle loan or lease                                                            11377
Money transfer, virtual currency, or money service                               10164
Payday loan, title loan, or personal loan                                         8659
Payday loan                                                                       5544
Money transfers                                                                   5354
Prepaid card                                                                      3819
Other financial service                                                           1059
Virtual currency                                                                    18
Name: count, dtype: int64

In [42]:
print(data['Company public response'].value_counts())

Company public response
Company has responded to the consumer and the CFPB and chooses not to provide a public response                            311852
Company believes it acted appropriately as authorized by contract or law                                                    61135
Company chooses not to provide a public response                                                                            52473
Company believes the complaint is the result of a misunderstanding                                                           5674
Company disputes the facts presented in the complaint                                                                        5257
Company believes complaint caused principally by actions of third party outside the control or direction of the company      3989
Company believes complaint is the result of an isolated error                                                                3728
Company believes complaint represents an opportunity for improvement to better serve consumers                               2618
Company can't verify or dispute the facts in the complaint                                                                   2295
Company believes complaint relates to a discontinued policy or procedure                                                       61
Name: count, dtype: int64

In [43]:
print(data['Tags'].value_counts())

Tags
Servicemember                    84654
Older American                   76981
Older American, Servicemember    14008
Name: count, dtype: int64

In [44]:
print(data['Consumer consent provided?'].value_counts())

Consumer consent provided?
Consent provided        383885
Consent not provided    285087
Other                    20482
Consent withdrawn         1200
Name: count, dtype: int64

In [45]:
print(data['Submitted via'].value_counts())

Submitted via
Web            945329
Referral       173640
Phone           76509
Postal mail     67522
Fax             18972
Email             383
Name: count, dtype: int64

In [46]:
print(data['Company response to consumer'].value_counts())

Company response to consumer
Closed with explanation            993221
Closed with non-monetary relief    158716
Closed with monetary relief         74243
Closed without relief               17868
Closed                              17611
In progress                          9277
Untimely response                    6108
Closed with relief                   5304
Name: count, dtype: int64

In [47]:
print(data['Timely response?'].value_counts())

Timely response?
Yes    1250162
No       32193
Name: count, dtype: int64

In [48]:
print(data['Consumer disputed?'].value_counts())

Consumer disputed?
No     620123
Yes    148378
Name: count, dtype: int64

In [49]:
print(data['Complaint ID'].is_unique)

True

In [50]:
data[data['Consumer Claim'].notnull()].head()

,Date received,Tag,Consumer Claim,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
29904,2019-03-23,"Credit reporting, credit repair services, or o...",The Summer of XX/XX/2018 I was denied a mortga...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",IL,<NA>,NaN,Consent provided,Web,2019-03-23,Closed with explanation,Yes,NaN,3189109
30629,2019-03-22,"Credit reporting, credit repair services, or o...",There are many mistakes appear in my report wi...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",VA,220XX,NaN,Consent provided,Web,2019-03-22,Closed with explanation,Yes,NaN,3187982
30735,2019-03-22,"Credit reporting, credit repair services, or o...",There are many mistakes appear in my report wi...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",TX,770XX,NaN,Consent provided,Web,2019-03-22,Closed with explanation,Yes,NaN,3187954
30795,2019-03-22,"Credit reporting, credit repair services, or o...",There are many mistakes appear in my report wi...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",TX,787XX,NaN,Consent provided,Web,2019-03-22,Closed with explanation,Yes,NaN,3188091
30807,2019-03-22,"Credit reporting, credit repair services, or o...",There are many mistakes appear in my report wi...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",CA,951XX,NaN,Consent provided,Web,2019-03-22,Closed with explanation,Yes,NaN,3188119